# Generated by Django 6.0.6 on 2026-09-17 01:09

import SignUp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1)),
                ('classification', models.CharField(choices=[], max_length=1)),
                ('age', models.CharField(choices=[('14', '1-14'), ('30', '15-30'), ('59', '31-59'), ('60', '60+')], max_length=2)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('visitor_type', models.CharField(choices=[('E', 'EXHIBITOR'), ('O', 'ORGANIZER / FACILITATOR'), ('P', 'PARTICIPANT / WALK-IN'), ('S', 'SPEAKER'), ('V', 'VOLUNTEER')], max_length=1)),
                ('activities', models.CharField(choices=[('GE', '2026 Grand TKME Exhibit'), ('SE', '2026 S&T Exhibit'), ('PS', 'Plenary Sessions'), ('PC', 'Innovation Pitch Competition')], max_length=2)),
                ('e_signature', models.ImageField(upload_to=SignUp.models.signature_path)),
            ],
        ),
    ]
