# Generated by Django 6.0.6 on 2026-09-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('1', 'NCR (National Capital Region)'), ('2', 'CAR (Cordillera Administrative Region)'), ('3', 'Region I (Ilocos Region)'), ('4', 'Region II (Cagayan Valley)'), ('5', 'Region III (Central Luzon)'), ('6', 'Region IV-A (CALABARZON)'), ('7', 'Region IV-B (MIMAROPA)'), ('8', 'Region V (Bicol Region)'), ('9', 'Region VI (Western Visayas)'), ('10', 'Region VII (Central Visayas)'), ('11', 'Region VIII (Eastern Visayas)'), ('12', 'Region IX (Zamboanga Peninsula)'), ('13', 'Region X (Northern Mindanao)'), ('14', 'Region XI (Davao Region)'), ('15', 'Region XII (SOCCSKSARGEN)'), ('16', 'Region XIII (CARAGA)'), ('17', 'BARMM (Bangsamoro)')], default=12, max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='activities',
            field=models.CharField(choices=[('exhibit-tkime', '2026 Grand TKME Exhibit'), ('exhibit-st', '2026 S&T Exhibit'), ('plenary', 'Plenary Sessions'), ('innovation-pitch', 'Innovation Pitch Competition')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(choices=[('1-14', '1 to 14'), ('15-30', '15 to 30'), ('31-59', '31 to 59'), ('60+', '60 upwards')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='classification',
            field=models.CharField(choices=[('business', 'Business / Entrepreneur'), ('government', 'Government Employee'), ('homemaker', 'Homemaker'), ('media', 'Media'), ('others', 'Others'), ('private', 'Private Organization'), ('student', 'Student / Academe')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='visitor_type',
            field=models.CharField(choices=[('exhibitor', 'EXHIBITOR'), ('organizer', 'ORGANIZER / FACILITATOR'), ('participant', 'PARTICIPANT / WALK-IN'), ('speaker', 'SPEAKER'), ('volunteer', 'VOLUNTEER')], max_length=11),
        ),
    ]
