# Generated by Django 6.0.6 on 2026-09-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0002_user_region_alter_user_activities_alter_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('1', 'NCR (National Capital Region)'), ('2', 'CAR (Cordillera Administrative Region)'), ('3', 'Region I (Ilocos Region)'), ('4', 'Region II (Cagayan Valley)'), ('5', 'Region III (Central Luzon)'), ('6', 'Region IV-A (CALABARZON)'), ('7', 'Region IV-B (MIMAROPA)'), ('8', 'Region V (Bicol Region)'), ('9', 'Region VI (Western Visayas)'), ('10', 'Region VII (Central Visayas)'), ('11', 'Region VIII (Eastern Visayas)'), ('12', 'Region IX (Zamboanga Peninsula)'), ('13', 'Region X (Northern Mindanao)'), ('14', 'Region XI (Davao Region)'), ('15', 'Region XII (SOCCSKSARGEN)'), ('16', 'Region XIII (CARAGA)'), ('17', 'BARMM (Bangsamoro)')], max_length=2),
        ),
    ]
