# Generated by Django 6.0.6 on 2026-09-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0003_alter_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='does_consent',
            field=models.BooleanField(default=False),
        ),
    ]
