# Generated by Django 6.0.6 on 2026-09-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0004_user_does_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='e_signature',
        ),
        migrations.AddField(
            model_name='user',
            name='signature_data',
            field=models.JSONField(default=None),
        ),
    ]
