# Generated by Django 6.0.6 on 2026-09-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0005_remove_user_e_signature_user_signature_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature_data',
            field=models.JSONField(),
        ),
    ]
