# Generated by Django 6.0.6 on 2026-09-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0006_alter_user_signature_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='ageRange',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='contactEmail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='middle_name',
            new_name='middleName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='does_consent',
            new_name='privacyConsent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='visitor_type',
            new_name='visitorType',
        ),
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
