# Generated by Django 6.0.6 on 2026-09-17 13:19

import SignUp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0007_rename_age_user_agerange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='e_signature',
            field=models.ImageField(default=None, upload_to=SignUp.models.signature_path),
        ),
    ]
